### ISSUE TITLE
css style for `document`

### ISSUE THREAD

**Issue by lazarusA** [SimonDanisch/Bonito.jl#265]
where should I pass the Styles for the main document? I tried in 

`Page(; style=Styles(,..))` 

and 

`App(; style=Styles(,...)` 

but none of them are the way ![mandalorian](https://github.com/user-attachments/assets/2f3d2eeb-43c0-4d41-af29-83e32277582c)

**Comment by SimonDanisch** [comment]
Just put it in the outermost div!

**Comment by SimonDanisch** [comment]
You can create the whole document with DOM.body/meta/html

**Comment by sprig** [comment]
I think the confusion might be due to a bug in how styles get included:

``` julia
julia> ss=Styles(CSS("height"=>"100%","width"=>"100%","background"=>"black"))
 {
  height: 100%;
  width: 100%;
  background: black;
}


julia> string(DOM.div(style=ss))
"<div style=\" {&#10;  height: 100%;&#10;  width: 100%;&#10;  background: black;&#10;}&#10;\"></div>"
```

And wrapping in `App` will not make a black page. On the other hand, directly writing the style as a literal string in `style=...` works.
This is Bonito v4.0.1 With Julia 1.11 on Arm Mac.

**Comment by sprig** [comment]
My apologies - in my case I was trying to render the html directly in order to push to electron (I know about the electron integration, but I preferred to manage the window myself). However, the page was still making calls to the bonito server, and they were getting blocked by cors. As far as I understand this was the cause of the error, since the page renders correctly both in browser and in electron when loading the url.
